server:
  port: 9999

spring:
  cloud:
    gateway:
      routes:
      - uri: lb://sca-user-center
        service:
        predicates:
        - Path=/user-center/**
        filters:
        - StripPrefix=1
      - uri: lb://sca-order
        predicates:
        - Path=/order/**
        filters:
        - StripPrefix=1
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: sca-gateway