server:
  port: 10001

management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
  application:
    name: user-center
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: sca-user-center
    sentinel:
      transport:
        dashboard: 127.0.0.1:12000
      eager: true
      datasource:
        userCenterFlow:
          file:
            file: 'classpath: flowrule.json'
            data-type: json
            rule-type: flow
    stream:
      rocketmq:
        binder:
          namesrv-addr: 127.0.0.1:9876
      bindings:
        output:
          destination: test-topic
          content-type: application/json
  jpa:
    database: H2
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    name: test
    url: jdbc:h2:mem:user-center
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.h2.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
